package com.carcompanion.companion.data.repo

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Persona asset-pack manifest.  Generated by `tools/build_assets_manifest.py`
 * during the release-assets GitHub Action and bundled inside the ZIP.
 *
 * After download the file lives at
 * `<external-files-dir>/assets/<persona>/manifest.json`. Its presence and
 * `version` field are the **only** signals the app uses to decide whether
 * assets are installed and current.
 *
 * Field names follow the Python schema literally so the same JSON can
 * round-trip without a separate adapter layer.
 */
@Serializable
data class AssetsManifest(
    val persona: String,
    val version: String,
    @SerialName("generated_at") val generatedAt: String,
    @SerialName("audio_count") val audioCount: Int,
    @SerialName("gif_count") val gifCount: Int,
    @SerialName("file_count") val fileCount: Int,
    @SerialName("total_size_bytes") val totalSizeBytes: Long,
    val files: List<AssetFile>,
) {
    @Serializable
    data class AssetFile(
        val path: String,
        val size: Long,
        val sha256: String,
    )
}

/**
 * Lightweight version comparison.  Tags follow `vMAJOR.MINOR.PATCH`
 * (the leading `v` is optional; missing trailing parts default to 0).
 * Returns negative / 0 / positive like `Comparable.compareTo`.
 */
fun compareAssetVersions(a: String, b: String): Int {
    fun parts(s: String): IntArray {
        val trimmed = s.removePrefix("v").removePrefix("V")
        val raw = trimmed.split('.', '-').take(3)
        val out = IntArray(3)
        raw.forEachIndexed { i, p ->
            out[i] = p.toIntOrNull() ?: 0
        }
        return out
    }
    val pa = parts(a)
    val pb = parts(b)
    for (i in 0..2) {
        val cmp = pa[i].compareTo(pb[i])
        if (cmp != 0) return cmp
    }
    return 0
}
